### ISSUE TITLE
Power off button does not work

### ISSUE THREAD

**Issue by PPLandry** [leapdroid-team/leapdroid#15]
Hi,
I've installed Leapdroid on 2 Windows 10 tablet PCs and the power off button (button bar on the right) does not work.
Closing the window does work but I suspect that the current state is not saved. As an example, the setting to use or not the physical keyboard is not saved, hence each time one powers off, one must go in settings to turn off the keyboard.
Thanks

**Comment by tonyyangle** [comment]
Fixed. Will be in the next release. Thanks.
