### ISSUE TITLE
Support screen rotation

### ISSUE THREAD

**Issue by PPLandry** [leapdroid-team/leapdroid#17]
Hi,
If the tablet is rotated (to portrait mode), the display is not updated correctly. I've use Virtualbox (for a dev. project) and it supports dynamic sizing, so it "should" be possible to do.
Thanks

**Comment by vtt** [comment]
How do you rotate to portrait mode?  I can't find the option to do so

**Comment by leapdroid** [comment]
Supported through version 1.6.1

**Comment by antranthien** [comment]
I'm using version 1.7.0 now and can't find the option to rotate the screen.

**Comment by duongjoshua** [comment]
Click on the Settings button on the toolbar. In the display tab, you'll see the option to turn the rotation on/off.

**Comment by antranthien** [comment]
It is turned on by default, but I don't see the button  to switch the screen between portrait/landscape modes in the right bar. 
![leapdroid](https://cloud.githubusercontent.com/assets/14801036/18886494/71037c84-84f0-11e6-942f-a16df781adf8.png)

**Comment by riffy13** [comment]
I can't figure out how to get this to rotate either. I've tried the on & off setting with no difference. I've even tried to force it to rotate with android apps with no success.

**Comment by timea-techgirl** [comment]
@PPLandry @vtt @antranthien @riffy13 
To get Portrait Mode:
Turn off Rotation from Leapdroid settings.
Enter the resolution as 800 x 1280
Enter the DPI as 320
Restart :)
