### ISSUE TITLE
How to change default screen resolution?

### ISSUE THREAD

**Issue by lovebdsobuj** [leapdroid-team/leapdroid#24]

**Comment by cosote** [comment]
use command line arguments -w for width and -h for height, e.g.
"C:\Program Files\Leapdroid\VM\LeapdroidVM.exe" -vfiber -novtcheck -w 900 -h 600 -s vm1 
I'm also using -novtcheck for custom RAM and CPU settings I've configured also and with this parameter those don't get reset to default settings...

**Comment by khanh8609vnz3** [comment]
And can you tell me how to custom Ram and CPU setting ?

**Comment by leapdroid** [comment]
You can change resolution through setting button on the side bar since 1.6.1

**Comment by lovebdsobuj** [comment]
Which is the button icon for changing screen resolution?
![screenshot_2016 09 13_19h23m23s_001_](https://cloud.githubusercontent.com/assets/10352682/18475313/c4e7b176-79e7-11e6-9b26-128d77481604.png)

**Comment by rellikpenguin** [comment]
I tried OpenGl but it crashes trying to start, i want to revert to direct x, isnt there a file i can modify?
