### ISSUE TITLE
[1.6.1.0] Power Button does not turn off the screen, instead functions as a second Back Button

### ISSUE THREAD

**Issue by Onihikage** [leapdroid-team/leapdroid#33]
In an older version (I believe 1.4.x, but I'm not sure) the power button would turn the screen off. This was useful as it was a quick way to reduce CPU time to 0.1% or lower, if I wanted to do something else without closing Leapdroid. Very good for multitasking.

Now, it performs the same functionality as the back button. Both the keyboard shortcut (Esc) and the direct power button on the side panel behave like hitting the back button. The back button itself behaves normally.

**Comment by duongjoshua** [comment]
Fixed. Will be in the next release.
