### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by Tatikoma** [leapdroid-team/leapdroid#40]
What a current status for the Linux version?

http://askubuntu.com/questions/804865/how-to-install-leapdroid-android-emulator
>>Internally, we did all development on Linux, for each build, we make Leapdroid to work first on Linux, then build for Windows. What is missing is the packaging which we are working on right now. We should release a Linux version late in August.

**Comment by tonyyangle** [comment]
We have already package our files to deb file, but we have met some issues to launch our viewer, still work on Linux version.

**Comment by abuhenasobuj** [comment]
@tonyyangle, Hi, Does the Linux version is ready? 
_Please share a leapdroid version for Linux._
