### ISSUE TITLE
Keyboard do not work

### ISSUE THREAD

**Issue by ale5000-git** [leapdroid-team/leapdroid#43]
Leapdroid 1.7.0.0 on a notebook with Windows 8.1.
Mouse works correctly but if I open search or browser I cannot write anything with the keyboard.

Backspace and arrows actually works but letters do not works.
The problem happens after switching the language of Android to Italian.

**Comment by duongjoshua** [comment]
The keyboard will not work if you switch the Android language input to Italian. You must use LeapdroidIME, as this service is used to intercept the keyboard.

**Comment by ale5000-git** [comment]
Is it possible to allow change the language of the interface without automatically switch also the keyboard?

**Comment by duongjoshua** [comment]
In the Settings, go to Language & Input, then click on Languages. You can change the language interface to Italian there.

**Comment by ale5000-git** [comment]
I have changed it and it changed also keyboard, I can change it back but would be better if it doesn't change also keyboard since other keyboard will not work.
