### ISSUE TITLE
Genymotion wallpapers on Leapdroid

### ISSUE THREAD

**Issue by Mendim** [leapdroid-team/leapdroid#7]
You forgot to change the Genymotion wallpapers on Leapdroid :)
Anyway.the Emulator realy is quick and stable.im using it now.as main emulator

**Comment by huisinro** [comment]
This wallpaper is from a Rockchip dongle, not from Genymotion. Perhaps, Genymotion happened to use the same one?

**Comment by leapdroid** [comment]
Removed. Thanks for letting us know.
